export const ABI_MUSIC = {
  MusicMarket: {
    address: '0x5F0Bf78E618702aB00d2503ee792fDa2d28Fd143',
    abi: [
      {
        inputs: [{ internalType: 'contract IMuc', name: 'muc', type: 'address' }],
        stateMutability: 'nonpayable',
        type: 'constructor',
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
          { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
        ],
        name: 'BuySong',
        type: 'event',
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
          { indexed: true, internalType: 'address', name: 'seller', type: 'address' },
          { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
          { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
          { indexed: false, internalType: 'string', name: 'uri', type: 'string' },
        ],
        name: 'ListSong',
        type: 'event',
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
          { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
        ],
        name: 'OwnershipTransferred',
        type: 'event',
      },
      {
        anonymous: false,
        inputs: [{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' }],
        name: 'PauseListSong',
        type: 'event',
      },
      {
        anonymous: false,
        inputs: [{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' }],
        name: 'UnpauseListSong',
        type: 'event',
      },
      {
        inputs: [],
        name: 'FEE',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
      },
      {
        inputs: [],
        name: 'owner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
      },
      {
        inputs: [],
        name: 'renounceOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
        name: 'song',
        outputs: [
          {
            components: [
              { internalType: 'uint256', name: 'id', type: 'uint256' },
              { internalType: 'uint256', name: 'price', type: 'uint256' },
              { internalType: 'uint256', name: 'amount', type: 'uint256' },
              { internalType: 'string', name: 'uri', type: 'string' },
              { internalType: 'address', name: 'seller', type: 'address' },
              { internalType: 'bool', name: 'paused', type: 'bool' },
            ],
            internalType: 'struct IMusicMarket.Song',
            name: '',
            type: 'tuple',
          },
        ],
        stateMutability: 'view',
        type: 'function',
      },
      {
        inputs: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'string', name: 'uri', type: 'string' },
        ],
        name: 'listSong',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        inputs: [
          { internalType: 'uint256[]', name: 'id', type: 'uint256[]' },
          { internalType: 'uint256[]', name: 'price', type: 'uint256[]' },
          { internalType: 'uint256[]', name: 'amount', type: 'uint256[]' },
          { internalType: 'string[]', name: 'uri', type: 'string[]' },
        ],
        name: 'listSongs',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        inputs: [
          { internalType: 'contract IMusic', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'uint256', name: 'deadline', type: 'uint256' },
          { internalType: 'uint8', name: 'v', type: 'uint8' },
          { internalType: 'bytes32', name: 'r', type: 'bytes32' },
          { internalType: 'bytes32', name: 's', type: 'bytes32' },
        ],
        name: 'buySong',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
        name: 'pauseListSong',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
        name: 'unpauseListSong',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        inputs: [],
        name: 'withdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
      },
    ],
    contractName: 'MusicMarket',
    input: ['0x4b137a387D2b4734013D6F78B4bC01aa25BD48bf'],
    path: 'music',
  },
};
